Request api limit
bitex-la/compliance pull request #198
Opened 2019-11-05 21:00 UTC by mdallago

2019-11-05 21:38 UTC, tmsrjs commented on app/admin/attachments.rb
> +      resource.person.id
Acá (y en las otras definiciones de `related_person`) nos podemos evitar un round-trip a la DB ya sea haciendo eager_load del `Person` o devolviendo `resource.person_id`.

2019-11-05 21:38 UTC, tmsrjs commented on app/controllers/application_controller.rb
> +    return if action_name == 'index'
Esto iría en `before_action :verify_request, except: :index`.

2019-11-05 21:38 UTC, tmsrjs commented on config/initializers/redis-objects.rb
> +module Redis::Objects::JsonMarshalling
Este módulo era para una versión vieja de `redis-objects` que no soportaba serializadores custom y se incluía en las clases definidas más abajo.
Si fuera necesario, ahora se puede usar https://github.com/nateware/redis-objects#custom-serialization

2019-11-05 21:38 UTC, tmsrjs commented on config/initializers/redis-objects.rb
> +  def key
Este método se usaba para prependear el namespace que usa rails en las keys pero, viendo que se usa `Redis` a pelo, podría volar sin problemas.

2019-11-07 17:17 UTC, tmsrjs commented on app/admin/observations.rb
> +    def related_person
Acá (y en las otras definiciones de `related_person` nos podemos traer todo en un solo round-trip a la DB haciendo `eager_load` del issue.
```
def scoped_collection
  super.eager_load(:issue)
end
```

2019-11-07 17:42 UTC, mdallago commented on app/controllers/application_controller.rb
> +    set = Redis::Set.new("request_limit:people:#{AdminUser.current_admin_user.id}:#{now_string}", :expireat => expire_at)
si me confundi con el expire comun que recibe segundos.

2019-11-07 20:35 UTC, tmsrjs reviewed
Buenísimo! Faltarían unos specs y estamos 👌

2019-11-07 20:37 UTC, mdallago commented
sisi, los deje para el final, hasta estabilizar el codigo...

2019-11-08 19:17 UTC, tmsrjs commented on .circleci/settings.yml
> +    cache_url: 'redis://localhost:6379/0/compliance'
Esto se me pasó: la segunda parte del path (`compliance`) se usa como namespace pero `Redis` a pelo no lo soporta, debería usarse `Redis::Store` como en cryptocambios o sacarle el namespace.
No está pinchando de casualidad, pero se puede prestar a confusión.

2019-11-08 19:21 UTC, mdallago commented on .circleci/settings.yml
> +    cache_url: 'redis://localhost:6379/0/compliance'
para usar Redis::Store necesito instalar redis-rails ??

2019-11-11 13:39 UTC, mdallago commented on .circleci/settings.yml
> +    cache_url: 'redis://localhost:6379/0/compliance'
en la docu de redis-rails dice que Rails 5.x ya tiene un redis cache incluido y que no se necesita usar mas el gem..

https://github.com/rails/rails/pull/31134

2019-11-11 14:29 UTC, mdallago commented on .circleci/settings.yml
> +    cache_url: 'redis://localhost:6379/0/compliance'
use directamente el gem redis-store

2019-11-13 20:54 UTC, tmsrjs commented on spec/helpers/shared_examples_for_api_endpoints.rb
> +  it "Can validate max people request limit on #{type} show" do
También deberíamos probar que se "resetea" el límite cuando cambia el día. La implementación actual lo hace parecer obvio pero puede cambiar.

2019-11-14 15:22 UTC, mdallago commented on spec/helpers/shared_examples_for_api_endpoints.rb
> +  it "Can validate max people request limit on #{type} show" do
dale, agrego ese spec

2019-11-14 16:34 UTC, tmsrjs commented on spec/helpers/shared_examples_for_api_endpoints.rb
> +    api_get "/#{type}/#{@one.id}"
Acá en realidad lo que queremos probar es que te permita obtener el que excedía el límite (`@four`) mas otros dos y que el cuarto lo rebota.

2019-11-20 20:42 UTC, tmsrjs requested changes

2019-11-20 20:42 UTC, tmsrjs commented on spec/factories/admin_user.rb
> +
Creo que estaría bueno que todos los otros factories tengan un `max_people_allowed` muy alto como para que siempre se ejercite esa parte del código e indirectamente checkear que todos los controllers (existentes y futuros) implementan `related_person`.

2019-11-20 20:42 UTC, tmsrjs commented on spec/helpers/shared_examples_for_api_endpoints.rb
> +    expect(json_response[:data][:id]).to eq(@three.id.to_s)
Acá estaría bueno probar que no hay límite si el usuario no tiene uno definido.
La única forma que se me ocurre es quitarle el límite al usuario y volver a pedir un recurso al que antes no tenía acceso.

2019-11-21 15:45 UTC, tmsrjs approved these changes

2019-11-21 17:26 UTC, nubis requested changes

2019-11-21 17:26 UTC, nubis commented on app/controllers/application_controller.rb
> +    if counter.increment <= limit
Hay alguna motivación para incrementarlo y luego decrementarlo?
Me había imaginado algo así:

return if set.member? person_id

if counter.increment >= limit
  return render body: nil, status: 400
end

counter.increment
set << person_id

2019-11-21 17:26 UTC, nubis commented on app/admin/admin_users.rb
>      column :otp_enabled
Para poder revisar el uso que hace cada usuario y ajustarlo a sus patrones normales, me gustaría poder ver acá cuantas personas lleva visitadas en el día.

2019-11-21 17:27 UTC, nubis commented
Dejo una nota por acá para recordar que antes de deployar esto tenemos que ver a que redis lo apuntamos. El firewall debería permitir acceder a los redis de elasticache de cryptocambios, usemos esos así tenemos menos cosas que monitorear, no @tmsrjs ?

2019-11-21 18:58 UTC, tmsrjs commented
> Dejo una nota por acá para recordar que antes de deployar esto tenemos que ver a que redis lo apuntamos. El firewall debería permitir acceder a los redis de elasticache de cryptocambios, usemos esos así tenemos menos cosas que monitorear, no @tmsrjs ?

Preferiría mantenerlo separado. Si empezamos a meter todo en el mismo lugar, no va a faltar el momento en que nos veamos tentados a leer data de la otra app solamente porque está en la misma DB, o que un bug en una app nos corrompa la otra.
En cuanto al monitoreo, creo que es despreciable el trabajo extra que agrega.

2019-11-21 19:11 UTC, mdallago commented on app/controllers/application_controller.rb
> +    if counter.increment <= limit
esta buena la sugerencia. nos ahorramos un roundtrip a redis. hablando con cocho vimos que aumenta la probabilidad de un race..pero no es tan grave. solo le haria 2 correcciones.. cambiaria el >= por > y borraria el 2do counter.increment, ya que no es necesario.

2019-11-26 14:27 UTC, merged