Admin tags
bitex-la/compliance pull request #237
Opened 2020-02-27 15:58 UTC by mdallago

Fixes https://github.com/bitex-la/storyboard/issues/836

2020-03-18 20:49 UTC, werner commented on app/controllers/api/person_taggings_controller.rb
> +    return resource if tags.empty?
Esto está un poco raro, devuelves resource si tags es empty, pero también si es nulo?, tal vez pudieras usar blank? así:

```ruby
return resource if AdminUser.current_admin_user&.active_tags.blank?
```
Además que me parece que tags no se vuelve a usar en otro lado.

2020-03-18 20:50 UTC, werner commented on app/controllers/api/person_taggings_controller.rb
> +    return collection if tags.empty?
Creo que aquí también aplica lo anterior, a menos que me esté equivocando al interpretar el código.

2020-03-19 14:22 UTC, mdallago commented on app/controllers/api/person_taggings_controller.rb
> +    return resource if tags.empty?
casualmente lo que tuve que agregar a este controller es algo que quiero borrar...pero no encontre una manera de hacerlo en el modelo....por eso queria ver si alguno se le ocurria algo mejor

2020-03-19 19:49 UTC, werner commented on spec/helpers/shared_examples_for_models.rb
> +        seed.update!(later_attrs)
¿faltan expects? o ¿tal vez la idea es que el update! y save! no generen errores?, aún así creo que es raro ver specs sin expects.

2020-03-19 19:51 UTC, werner commented on spec/helpers/shared_examples_for_models.rb
> +        seed_type_const.find(seed4.id)
Creo que aquí faltan expects también.

2020-03-20 12:59 UTC, mdallago commented on spec/helpers/shared_examples_for_models.rb
> +        seed_type_const.find(seed4.id)
agregados

2020-03-20 12:59 UTC, mdallago commented on spec/helpers/shared_examples_for_models.rb
> +        seed.update!(later_attrs)
agregados

2020-03-20 17:48 UTC, mdallago commented on app/controllers/api/person_taggings_controller.rb
> +    return resource if tags.empty?
aplique el cambio provisoriamente hasta encontrar una mejor solucion

2020-03-20 17:48 UTC, mdallago commented on app/controllers/api/person_taggings_controller.rb
> +    return collection if tags.empty?
aplique el cambio provisoriamente hasta encontrar una mejor solucion

2020-03-20 17:58 UTC, werner approved these changes

2020-03-25 20:16 UTC, werner commented on app/models/admin_user.rb
> +    return true if result.empty?
Si entiendo bien la función creo que se puede componer de una manera más fácil:
```ruby
result = active_tags
result.empty? || result.include? tag.id
```
Debido a que Ruby sigue la filosofía del short-circuit creo que la segunda condición no la evalúa si la primera es verdadera.

2020-03-26 13:38 UTC, werner approved these changes

2020-04-28 16:01 UTC, nubis commented on app/admin/people.rb
> +      resource.load_admin_tags
build_admin_tag_suggestions if resource.new_record?

2020-04-28 18:18 UTC, mdallago commented on app/admin/people.rb
> +      resource.load_admin_tags
listo

2020-05-05 08:53 UTC, nubis requested changes
Muy repetitivos los specs, me temo que si hoy algún bug oculto en alguna repeticón no lo vi

2020-05-05 08:53 UTC, nubis commented on spec/models/task_spec.rb
> +    it "allow task creation without person tags if admin has no tags" do
este tambien puede ser redundante

2020-05-05 08:53 UTC, nubis commented on spec/models/task_spec.rb
> +
map sobre los 4 persons

2020-05-05 08:53 UTC, nubis commented on spec/models/workflow_spec.rb
> +      expect { Issue.find(issue2.id) }.to raise_error(ActiveRecord::RecordNotFound)
issue2.reload

2020-05-05 08:53 UTC, nubis commented on spec/models/workflow_spec.rb
> +      workflow.save!
workflow.update!

2020-05-05 08:53 UTC, nubis commented on spec/models/workflow_spec.rb
> +      workflow1, workflow2, workflow3, workflow4 = setup_for_admin_tags_spec
este spec además es candidato a shared example.

2020-05-05 08:53 UTC, nubis commented on spec/requests/api/admin_user_taggings_spec.rb
> +    json_response.should >= {
expect(api_response).to have_attributes

2020-05-05 08:53 UTC, nubis commented on spec/requests/api/admin_user_taggings_spec.rb
> +    json_response.should >= {
u otro expect

2020-05-05 08:53 UTC, nubis commented on spec/requests/api/attachments_spec.rb
> +      admin_user.save!
no se si hace falta guardarlo. con inverse_of seguro que no.

2020-05-05 08:53 UTC, nubis commented on spec/requests/api/attachments_spec.rb
> +      person1 = create(:full_person_tagging).person
DRY

2020-05-05 08:53 UTC, nubis commented on spec/requests/api/fund_deposits_spec.rb
> +    it "allow fund deposit creation only with person valid admin tags" do
en estos nos podemos explayar con un comment sobre el escenario. Si lo ponemos en shared example se entiende mejor la idea

2020-05-05 08:53 UTC, nubis commented on spec/requests/api/fund_withdrawals_spec.rb
> +  describe "When filter by admin tags" do
DRY

2020-05-05 08:53 UTC, nubis commented on spec/requests/api/issue_taggings_spec.rb
> +    it "allow issue tagging creation only with person valid admin tags" do
DRY

2020-05-05 08:53 UTC, nubis commented on spec/requests/api/issues_spec.rb
> +  describe "When filter by admin tags" do
DRY

2020-05-05 08:53 UTC, nubis commented on spec/requests/api/observations_spec.rb
> +    it "allow observation creation only with person valid admin tags" do
DRY

2020-05-05 15:08 UTC, mdallago commented on app/models/person.rb
> +    AdminUser.current_admin_user&.add_tag(tag)
aca no me gusta que desde person se acceda directo a AdminUserTagging, pq se rompe un poco la encapsulacion...prefiero delegarle la tarea al AdminUser que sabe como administrar sus tags...

2020-05-11 13:05 UTC, mdallago commented on app/models/attachment.rb
> +    # TODO: I don't know why the person is not set on a before_validation.
este TODO ya se puede eliminar @nubis

2020-05-11 15:20 UTC, mdallago commented on spec/helpers/shared_examples_for_api_endpoints.rb
> +      it "allow #{seed_type} creation without person tags if admin has tags" do
creo que todos los test de api se podrian borrar, ya que los cambios estan probados en los model specs y no hay cambios en los controllers

2020-05-15 04:25 UTC, tmsrjs commented on app/models/admin_user.rb
> +      .exists?
Creo que acá podemos sacrificar velocidad por legibilidad.
```suggestion
    !admin_user_taggings.exists? ||
      admin_user_taggings.where(tag: tag).exists?
```

2020-05-20 01:49 UTC, tmsrjs requested changes

2020-05-20 01:49 UTC, tmsrjs commented on app/models/person.rb
> +  def self.default_scope
En general está desalentado redefinir `default_scope`, puede hacer que las queries se comporten de manera contra-intuitiva.
En cambio lo que se recomienda es definir un scope y utilizarlo de manera explícita donde sea necesario.
https://apidock.com/rails/ActiveRecord/Scoping/Named/ClassMethods/scope

2020-05-20 01:49 UTC, tmsrjs commented on app/models/fund_transfer.rb
> +    where(source_person_id: Person.all)
Esta query se ve rara y es contra-intuitiva.
A simple vista parece que siempre va a devolver todos los `FundTransfer`, no queda claro que en realidad depende de como esté construida la query de `Person.all` que a su vez depende de un `default_scope` dinámico.
Me parece que quedaría más claro definir un scope en `Person` y usarlo en vez de `Person.all`.
https://apidock.com/rails/ActiveRecord/Scoping/Named/ClassMethods/scope

2020-05-20 01:49 UTC, tmsrjs commented on app/models/person_scopeable.rb
> +    def default_scope
Este `default_scope` pareciera ser utilizado solamente para el admin.
Creo que lo mejor sería moverlo a los controllers redefiniendo el método `scoped_collection` donde sea necesario.
Por otro lado, redefinir `default_scope` para tantos models puede traer comportamiento inesperado en entornos donde no hay un `AdminUser`, como puede ser un proceso de background, un arreglo o consulta manual en la consola o durante una migración.

2020-05-20 01:49 UTC, tmsrjs commented on spec/helpers/admin_user_helpers.rb
> +    result
```suggestion
    yield
  ensure
    AdminUser.current_admin_user = old_admin
```

2020-05-20 01:49 UTC, tmsrjs commented on spec/models/person_spec.rb
> +    let(:admin_user) { AdminUser.current_admin_user = create(:admin_user) }
Que el comportamiento del modelo dependa de esta pseudo variable global me parece medio un anti-pattern.
Lo que se me ocurre que se puede hacer es usar métodos especializados que reciben el `AdminUser` donde se necesite para tomar alguna decisión y mover el scoping a los controllers donde estamos seguros que siempre hay un `AdminUser`

2020-05-20 15:55 UTC, mdallago commented on app/models/task.rb
> +  default_scope { joins(:workflow, workflow: :issue) }
se agrego comentario para aclarar su uso

2020-05-20 15:56 UTC, mdallago commented on app/models/issue_tagging.rb
> +  default_scope { joins(:issue).distinct }
se agrego comentario para aclarar su uso

2020-05-20 15:56 UTC, mdallago commented on app/models/workflow.rb
> +  default_scope { joins(:issue) }
se agrego comentario para aclarar su uso

2020-05-20 15:56 UTC, mdallago commented on lib/garden.rb
> +      default_scope { joins(:issue).distinct }
se agrego comentario para aclarar su uso

2020-05-20 15:58 UTC, mdallago commented on spec/models/person_spec.rb
> +    let(:admin_user) { AdminUser.current_admin_user = create(:admin_user) }
por ahora lo dejamos asi, hasta resolver como manejar el user de contexto https://github.com/bitex-la/storyboard/issues/313

2020-05-20 16:02 UTC, mdallago commented on app/models/fund_transfer.rb
> +    where(source_person_id: Person.all)
voy a definir un nuevo scope en Person y reemplazar el Person.all asi queda explicito

2020-05-20 16:04 UTC, mdallago commented on app/models/person.rb
> +  def self.default_scope
por ahora lo dejamos asi

2020-05-20 16:05 UTC, mdallago commented on app/models/person.rb
> +  def self.default_scope
solo agregue un comment para aclarar su uso

2020-05-20 16:07 UTC, mdallago commented on app/models/person_scopeable.rb
> +    def default_scope
lo cambie para que use el nuevo scope definido en Person

2020-05-20 17:15 UTC, tmsrjs approved these changes

2020-05-21 09:47 UTC, nubis approved these changes

2020-05-21 09:47 UTC, nubis commented
@mdallago cuales son los DeployNotes de esto?

2020-05-21 09:48 UTC, merged

2020-05-21 12:41 UTC, mdallago commented
estan escritas en la issue