Bootstrap FundTransfer resource
bitex-la/compliance pull request #246
Opened 2020-03-24 18:31 UTC by smtx

Solves https://github.com/bitex-la/compliance/issues/242

2020-03-25 13:18 UTC, mdallago requested changes

2020-03-25 13:18 UTC, mdallago commented on db/schema.rb
> +    t.index ["person_id", "country"], name: "index_fund_withdrawals_on_person_id_and_country"
esta linea no va en este branch

2020-03-25 13:18 UTC, mdallago commented on app/models/person.rb
> +  has_many :receive_transfers, :class_name => 'FundTransfer', :foreign_key => 'target_person_id'
estos nombres los pondria en pasado

2020-03-25 13:18 UTC, mdallago commented on db/migrate/20200324175440_create_fund_transfers.rb
> +      t.bigint :source_person_id
poner los nullables en false, todos los campos son obligatorios

2020-03-25 13:18 UTC, mdallago commented on db/migrate/20200324175440_create_fund_transfers.rb
> +      t.bigint :source_person_id
source person y target persons deberian ser references

2020-03-25 13:18 UTC, mdallago commented on spec/requests/api/fund_transfers_spec.rb
> +      api_response.data.attributes.amount.should == '20000.0'
cambiemos should x expect

2020-03-25 13:18 UTC, mdallago commented on test/fixtures/fund_transfers.yml
> +one:
que es esto ?

2020-03-25 13:18 UTC, mdallago commented on test/models/fund_transfer_test.rb
> +class FundTransferTest < ActiveSupport::TestCase
que es esto ?

2020-03-25 13:19 UTC, mdallago commented
Recorda usar Fixes en vez de Solves en la descripcion del PR, github funciona distinto cuando se usa Fixes

2020-03-27 13:31 UTC, mdallago commented on db/migrate/20200324175440_create_fund_transfers.rb
> +      t.datetime :transfer_date
falto null: false

2020-03-30 15:46 UTC, mdallago commented on db/migrate/20200324175440_create_fund_transfers.rb
> +      t.string :external_id
pongamosle null:false tambien a external_id

2020-03-30 16:19 UTC, smtx commented on db/migrate/20200324175440_create_fund_transfers.rb
> +      t.string :external_id
Ok, se lo pongo tambien a withdrawals y deposits que tampoco tienen?

2020-03-30 16:28 UTC, mdallago commented on db/migrate/20200324175440_create_fund_transfers.rb
> +      t.string :external_id
a withdrawal si...a fund deposit no..pq no quiero romper nada viejo

2020-03-30 16:50 UTC, mdallago commented on app/models/fund_transfer.rb
> +
agregar validates :external_id, presence: true

2020-03-30 16:51 UTC, mdallago commented on spec/models/fund_transfer_spec.rb
> +      currency source_person target_person amount exchange_rate_adjusted_amount transfer_date
falta external_id

2020-03-30 18:27 UTC, mdallago approved these changes

2020-04-02 11:40 UTC, merged