Fix destroy permissions
bitex-la/compliance pull request #265
Opened 2020-06-04 19:56 UTC by mdallago

Fixes https://github.com/bitex-la/storyboard/issues/1060

2020-06-06 15:53 UTC, tmsrjs requested changes

2020-06-06 15:53 UTC, tmsrjs commented on spec/features/admin_restricted_spec.rb
> +    Capybara.using_wait_time(10) do
Por qué es necesario usar `Capybara.using_wait_time`?
La página es estática y ya está totalmente renderizada en este punto, el wait implícito debería alcanzar.

2020-06-06 15:59 UTC, mdallago commented
El remove, manda el request en el momento y recarga la página... Y suele tardar más q el timeout default..por eso tuve a aumentarlo un poquito 

Enviado desde Yahoo Mail para Android 
 
  El sáb., 6 de jun. de 2020 a la(s) 12:53, Tomas Rojas<notifications@github.com> escribió:   


@tmsrjs requested changes on this pull request.

In spec/features/admin_restricted_spec.rb:
>      within(".action_items") do
       expect(page).to_not have_selector(:link_or_button, 'Approve')
       expect(page).to_not have_selector(:link_or_button, 'Dismiss')
       expect(page).to_not have_selector(:link_or_button, 'Abandon')
       expect(page).to_not have_selector(:link_or_button, 'Reject')
     end
+
+    click_link "Edit"
+
+    find('li[title="Domiciles"] a').click
+
+    accept_alert do
+      click_link 'Remove'
+    end
+
+    Capybara.using_wait_time(10) do

Por qué es necesario usar Capybara.using_wait_time?
La página es estática y ya está totalmente renderizada en este punto, el wait implícito debería alcanzar.

—
You are receiving this because you were assigned.
Reply to this email directly, view it on GitHub, or unsubscribe.

2020-06-08 10:21 UTC, nubis commented on spec/features/admin_restricted_spec.rb
> +    Capybara.using_wait_time(10) do
Eso levanta otras preguntas: ¿Por que tarda más de lo normal en borrar un seed en test? ¿Capybara no esperaba a que se termine de cargar la siguiente página luego de un click link?

2020-06-08 17:33 UTC, mdallago commented on spec/features/admin_restricted_spec.rb
> +    Capybara.using_wait_time(10) do
el remove devuelve un 302 y se realia un 2do request a /edit por eso el tiempo total es superior. Eso hace que capybara no este en control del 2do request y no detecta que ya termino.
Hable con @tmsrjs y lo vamos a dejar asi.

2020-06-08 17:43 UTC, merged