Do not show future observations
bitex-la/compliance pull request #278
Opened 2020-08-25 20:49 UTC by mdallago

https://github.com/bitex-la/storyboard/issues/1201

2020-08-26 16:53 UTC, tmsrjs requested changes

2020-08-26 16:53 UTC, tmsrjs commented on app/models/observation.rb
> +    where("issue_id in (?)", Issue.current.select(:id))
The Rails Way:
```suggestion
    merge(Issue.current)
```

2020-08-26 16:53 UTC, tmsrjs commented on spec/models/observation_spec.rb
> +  it "current scope only include non future issues" do
Habría que agregarle a este spec (o hacer uno nuevo) que demuestre que se incluyen los `Observation` una vez llegada la fecha del `Issue` futuro.

2020-09-02 15:56 UTC, fpelliccioni approved these changes

2020-09-03 20:17 UTC, merged