Allows external database configuration through env variables
bitex-la/compliance pull request #299
Opened 2020-10-31 22:31 UTC by bonzofenix

2020-11-02 14:10 UTC, mdallago commented on Procfile
> +web: bundle exec rails s
es necesario este cambio ?

2020-11-02 14:11 UTC, mdallago commented on Procfile
> +web: bundle exec rails s
como configuras el puerto ?

2020-11-02 17:57 UTC, mdallago commented on Procfile
> +web: bundle exec rails s
igual ni siquiera se para que necesitamos el procfile..no se si se sigue usando

2020-11-02 17:58 UTC, mdallago commented on Procfile
> +web: bundle exec rails s
vos necesitas el procfile para CF ?

2020-11-03 19:57 UTC, mdallago commented on config/settings.example.yml
> +    access_key: <%= ENV.fetch('SES_ACCESS_KEY', some_access_key) %>
cambiar el formato a <%= ENV.fetch("SES_ACCESS_KEY") { "some_access_key" } %>

2020-11-03 19:57 UTC, mdallago requested changes
ver comments para todas las keys

2020-11-06 20:37 UTC, bonzofenix commented
PR actualizado con el contenido de master @mdallago

2020-11-09 15:34 UTC, werner commented on Gemfile
> +gem 'rake'
¿es necesario indicar esta gema?, creo que viene incluida en Rails.

2020-11-09 15:35 UTC, mdallago commented on Gemfile
> +gem 'rake'
@bonzofenix

2020-11-09 20:21 UTC, mdallago commented
Duplicated of https://github.com/bitex-la/compliance/pull/310

2020-11-09 20:21 UTC, closed without merging