Change webdrivers to download geckodrivers most recent version
bitex-la/compliance pull request #309
Opened 2020-11-05 18:08 UTC by matiasgarcia

Fixes https://github.com/bitex-la/compliance/issues/308

2020-11-05 20:45 UTC, mdallago requested changes
agrega la parte del update automatico en los specs

2020-11-05 20:51 UTC, matiasgarcia commented
@mdallago acá no tenemos webmock por lo que no debería ser necesario, pero lo dejé listo para que sea lo primero que hace ni bien se carga la suite

2020-11-05 20:54 UTC, mdallago commented
@matiasgarcia si lo se..es para que se mantengan actualizadas las maquinas de los devs...

2020-11-06 12:55 UTC, mdallago requested changes
fallo el build https://app.circleci.com/pipelines/github/bitex-la/compliance/465/workflows/410c5fdc-27db-40d6-8c4e-75b7843d3376/jobs/1917

2020-11-06 17:07 UTC, mdallago approved these changes

2020-11-06 17:07 UTC, merged