Avoid transition from observed to any state if observations are not answered
bitex-la/compliance pull request #322
Opened 2020-12-11 18:44 UTC by werner

fixes: https://github.com/bitex-la/storyboard/issues/1438

2020-12-14 18:01 UTC, mdallago requested changes

2020-12-14 18:01 UTC, mdallago commented on app/models/issue.rb
> +      transitions from: %i[observed draft new answered],
la validarion tiene que ser unicamente en transiciones a estados finales

2020-12-14 18:01 UTC, mdallago commented on app/models/issue.rb
> +      transitions from: %i[draft new answered approved],
el guard se ejecuta despues del before...por ende pueden quedar seeds pasados a frutos incorrectamente

2020-12-14 20:57 UTC, werner commented on app/models/issue.rb
> +      transitions from: %i[observed draft new answered],
Para confirmar, los estados finales son: dismissed, rejected, approved y abandoned?

2020-12-14 20:58 UTC, mdallago commented on app/models/issue.rb
> +      transitions from: %i[observed draft new answered],
correcto

2020-12-15 13:31 UTC, werner commented on app/models/issue.rb
> +      transitions from: %i[draft new answered approved],
Pensando en que como funciona ahora este workflow, no sería lógico que el método `harvest_all!` se ejecuté después de aprobarse?, de esta forma se puede conservar el guard en este evento.

2020-12-15 13:33 UTC, mdallago commented on app/models/issue.rb
> +      transitions from: %i[draft new answered approved],
prefiero no tocar ese comportamiento. si harvest falla la issue no se aprueba

2020-12-15 13:39 UTC, werner commented on app/models/issue.rb
> +      transitions from: %i[draft new answered approved],
El tema es que ahora no sé que hacer, por que si muevo el método para el before, tendría que hacer un raise de la excepción `AASM::InvalidTransition` lo cual es complicado por que exige parámetros que no se pueden acceder desde aquí, la otra alternativa es mover el método `observations_answered?` para before en todos los eventos y retornar false, es decir, no procede la transición y falla silenciosamente, pero no se si es el comportamiento deseado.

2020-12-15 13:43 UTC, mdallago commented on app/models/issue.rb
> +      transitions from: %i[draft new answered approved],
quizas lo podemos resolver con un validate en el modelo sin tocar las transiciones...sino me equivoco actualmente existe uan validacion que no te deja aprobar un issue si tiene observaciones sin responder..deberiamos replicar ese comportamiento para el resto de los estados finales

2020-12-15 20:54 UTC, werner commented on app/models/issue.rb
> +      transitions from: %i[draft new answered approved],
Ahora que lo veo bien, creo que no es necesario el guard en approve por que no puede pasar de observed a approved.

2020-12-15 21:13 UTC, mdallago commented on app/models/issue.rb
> +      transitions from: %i[observed draft new answered], to: :answered
podras volver esta parte al original asi no me los marca github como cambios....

2020-12-17 20:45 UTC, mdallago approved these changes

2020-12-17 20:45 UTC, merged