Add pending tab to people admin
bitex-la/compliance pull request #339
Opened 2021-02-15 22:01 UTC by tmsrjs

Fixes bitex-la/storyboard#1531

2021-02-17 12:16 UTC, werner commented
Puede ser bueno tener un feature spec para los filtros del panel admin.

2021-02-17 16:08 UTC, mdallago commented on app/admin/people.rb
> +      (NaturalDocket.current.pluck(:nationality) +
es necesario mostrar únicamente los países para los que existen datos ? pq es bastante ineficiente tener q consultar esto cada vez que se entra al admin de permisos e issues...

2021-02-17 20:51 UTC, mdallago requested changes
- [ ] Agregar country validator en nationality NaturalDocket
- [ ] Validar que la lista de países traducidos este completa
- [ ] Cargar filtros con lista de países estática

2021-02-18 16:15 UTC, mdallago commented on app/admin/issues_dashboard.rb
> +    url: 'people/search_country',
@tmsrjs @werner proba varias cosas para evitar hardcodear esta url y no funciona ninguna...saben como resolverlo ?

2021-02-18 16:16 UTC, werner commented on app/admin/issues_dashboard.rb
> +    url: 'people/search_country',
no funciona agregando la url a routes.rb?

2021-02-18 16:18 UTC, mdallago commented on app/admin/issues_dashboard.rb
> +    url: 'people/search_country',
mmm , la url funciona..lo q yo quiero es q me funcione el helper del estilo search_country_people_path

2021-02-18 19:17 UTC, tmsrjs commented on app/admin/issues_dashboard.rb
> +    url: 'people/search_country',
En este scope no se puede usar el helper porque todavía no está definido.
Lo que se podría hacer es monkeypatchear los métodos `autocomplete_field` y `autocomplete_field_tag` para que `url` pueda ser un `proc`, de la misma manera que hicieron [acá](https://github.com/activeadmin/activeadmin/pull/5029) para `input_html`.
Ambos métodos están definidos por el gem `rails-jquery-autocomplete` en https://github.com/risuiowa/rails-jquery-autocomplete/blob/master/lib/rails-jquery-autocomplete/form_helper.rb.

2021-02-18 20:54 UTC, mdallago commented on app/admin/issues_dashboard.rb
> +    url: 'people/search_country',
excelente! gracias!

2021-02-18 20:55 UTC, mdallago approved these changes, later dismissed

2021-02-23 15:56 UTC, werner commented on config/initializers/active_admin.rb
> +module ActionView
Creo que seria bueno un feature spec para probar esta funcionalidad

2021-02-25 15:45 UTC, mdallago commented on config/initializers/active_admin.rb
> +module ActionView
@werner podras agregar el feature spec que comentas ?

2021-02-25 20:27 UTC, mdallago approved these changes

2021-02-25 20:28 UTC, merged