Add regulated_entity and operations_with_third_party_funds to legal entity dockets
bitex-la/compliance pull request #343
Opened 2021-03-02 13:18 UTC by werner

fixes: https://github.com/bitex-la/storyboard/issues/1595

2021-03-02 18:01 UTC, mdallago requested changes
agregar api specs

2021-03-03 14:53 UTC, werner commented
¿Que tipo de api specs requiere este issue? @mdallago

2021-03-03 14:58 UTC, mdallago commented
> ¿Que tipo de api specs requiere este issue? @mdallago

validar que se guarden los nuevos campos en un alta, y que lleguen los campos en el json cuando se hace un index o get individual

2021-03-04 15:32 UTC, mdallago commented on spec/requests/api/legal_entity_dockets_spec.rb
> +  describe 'regulated_entity and operations_with_third_party_funds' do
acabo de ver que esto se esta probando en los shared examples...asi que lo podemos borrar

2021-03-04 20:46 UTC, mdallago approved these changes

2021-03-04 20:47 UTC, merged