Now it checks for observations for client scope and include issue obs…
bitex-la/compliance pull request #384
Opened 2021-11-16 15:55 UTC by fbravo-bitex

Fixes https://github.com/bitex-la/storyboard/issues/2284

Agregamos cambios para contemplar observaciones a nivel Issue (no asociadas a un seed) y filtrado para observaciones de scope client y sin respuesta

2021-11-16 16:37 UTC, matiasgarcia requested changes
Le podemos agregar un spec para testear que:

1. `all_observations` retorne sólo observaciones de tipo client y new ?
2. `all_observations` incluya las observaciones que no están asociadas a ningún seed (observable = nil)
3. `all_observations` no retorne observaciones que sean de otro tipo (robot, admin)

2021-11-16 18:40 UTC, fbravo-bitex commented
Agregados los specs

2021-11-17 15:05 UTC, matiasgarcia commented on spec/models/issue_spec.rb
> +      end
Mi sugerencia es "no asumir" lo que hace el factory, ya que en el test tiene que ser visible "el estado que el objeto tiene que tener para testear lo que queremos testear". Entonces, si la observación no DEBE tener `observable`, forcemos acá  `observable: nil`.

2021-11-17 17:34 UTC, fbravo-bitex commented on spec/models/issue_spec.rb
> +      end
Ahi quedó explicitado el `observable: nil`.

2021-11-17 17:50 UTC, matiasgarcia approved these changes

2021-11-17 17:51 UTC, merged