Added reply validations for observations endpoint
bitex-la/compliance pull request #391
Opened 2021-12-20 19:36 UTC by fbravo-bitex

Fixes https://github.com/bitex-la/storyboard/issues/2420

# This PR
Agregamos una validación para cuando se trata de responder una observación con espacios en blanco. Utilizo validación dependiente de contexto para que impacte solamente en el endpoint asociado, si no impactaría en todos los updates de `Observation` donde si es válido que la reply esté vacía.

2021-12-20 20:23 UTC, matiasgarcia reviewed
¿La validación del reply no debería ser al transicionar a estado answered?

El `presence: true` es suficiente para manejar el caso de que te manden:

`reply: '      '` como indicó Nahuel? Para mi tenemos que hacer un https://apidock.com/rails/ActiveSupport/CoreExtensions/String/Filters/squish para eliminar espacios de más.

2021-12-20 20:23 UTC, matiasgarcia commented on app/models/observation.rb
> +  validates :reply, presence: true, on: :observation_reply
Tenemos que usar un contexto especial para ésto? Por qué?

2021-12-20 20:30 UTC, fbravo-bitex commented on app/models/observation.rb
> +  validates :reply, presence: true, on: :observation_reply
Si no uso un contexto, aplicaría la validación ante todo `update` de la `Observation`. Entiendo que una `Observation` se crea con `reply` vacía, por lo que en sí es un valor válido. Entonces si ante cualquier update se valida que la `reply` no esté vacía, no se podría actualizar información de estas observaciones (cambiar el `scope`, actualizar la `note`, etc).

2021-12-20 20:44 UTC, matiasgarcia commented on app/models/observation.rb
> +  validates :reply, presence: true, on: :observation_reply
Deberías evaluar que la `reply` esté "presente" (siendo presente que no tenga whitespaces al pedo) cuando está transicionando a estado `answered`. 

¿No podemos hacer eso?

2021-12-20 20:49 UTC, fbravo-bitex commented on app/models/observation.rb
> +  validates :reply, presence: true, on: :observation_reply
Y la idea sería levantar un error si no está presente? De ser así, podría simplemente validar la presencia de `reply` en el controller como pensaba inicialmente.

2021-12-20 21:00 UTC, matiasgarcia commented on app/models/observation.rb
> +  validates :reply, presence: true, on: :observation_reply
En base a ésto que corre en un before_save:

https://github.com/bitex-la/compliance/blob/master/app/models/observation.rb#L89

No podemos hacer una validación que:
1. Chequee may_answer?. Si da OK, seguir, sino, retornar.
2. Chequee el reply, si el `reply` está vacío, agregar error.
3. Si el reply está ok, no agrega errores.

"reply vacío" debería de alguna manera ignorar los casos como contestar `reply: '        '`. Mi sugerencia es usar https://apidock.com/rails/ActiveSupport/CoreExtensions/String/Filters/squish que remueve los whitespaces al pedo, pero manejalo como quieras.

2021-12-27 13:28 UTC, matiasgarcia reviewed
@fbravo-bitex me gustaría que no añadamos un endpoint nuevo para ésto, no podemos usar el que ya tenemos?

Quisiera evitar otro cambio en el frontend.

2021-12-27 15:41 UTC, fbravo-bitex commented
> @fbravo-bitex me gustaría que no añadamos un endpoint nuevo para ésto, no podemos usar el que ya tenemos?
> 
> Quisiera evitar otro cambio en el frontend.

Removí el nuevo endpoint del controller y agregué la inferencia del contexto para el save dependiendo de si se pasa el parámetro `reply` o no

2021-12-27 16:12 UTC, matiasgarcia requested changes
Tal vez estoy hilando fino, pero tanto params[:data] puede ser `nil` como `attributes` ser `nil`, si el usuario manda un payload equivocado.

Tal vez convenga usar algo como dig?

2021-12-28 13:26 UTC, matiasgarcia commented on app/controllers/api/observations_controller.rb
> +    :observation_reply if params.dig(:data, :attributes, :reply)
`context` puede ser `nil`?

2021-12-28 13:27 UTC, matiasgarcia approved these changes
`

2021-12-28 13:27 UTC, merged

2021-12-28 13:28 UTC, fbravo-bitex commented on app/controllers/api/observations_controller.rb
> +    :observation_reply if params.dig(:data, :attributes, :reply)
Si, en el caso de que sea `nil`, no aplica un `context` en el `save` así que no aplica la validación del `reply` que estoy agregando en este PR