[BX-50] Feature/add ipt
bitex-la/compliance pull request #397
Opened 2022-05-10 18:16 UTC by gallottohugo

Fixes https://bitex.atlassian.net/browse/BX-50

2022-05-10 19:10 UTC, matiasgarcia reviewed
El Allowance y el AllowanceSeed no deberian tener valor default en el IPT, acordate que habiamos dicho que podia ser null.

En el caso de la Person es distinto porque estamos backfilleando la data.

_Si_ podemos, cambiemos ipt a TPI (transactional profile index) que seria la tradu ok en ingles. Esto con baja prioridad.


Veo que el CI está roto, probablemente falte algun driver de selenium

2022-05-10 19:10 UTC, matiasgarcia commented on db/migrate/20220510150922_add_ipt_to_allowances.rb
> +    add_column :allowances, :ipt, :integer, :default => 0
Me parece que en este caso ipt para Allowances deberia poder ser null.

2022-05-10 19:10 UTC, matiasgarcia commented on db/migrate/20220510151322_add_ipt_to_allowance_seeds.rb
> +    add_column :allowance_seeds, :ipt, :integer, :default => 0
Idem arriba.

2022-05-10 19:10 UTC, matiasgarcia commented on app/models/person.rb
> +  enum ipt: %i(usd_0
Tal vez lo más semantico acá es "unknown"? Este seria el valor adicional que agregamos para lo que esta cargado en la bdd, no?

2022-05-10 19:10 UTC, matiasgarcia commented on spec/models/allowance_spec.rb
> +  end
Faltaria probar el caso de que le mandes un null ipt y el Person no cambie.

2022-05-10 19:10 UTC, matiasgarcia commented on db/migrate/20220509152606_add_ipt_to_people.rb
> +    add_column :people, :ipt, :integer, :default => 0
Si ponemos un campo default, podemos agregar el constraint de no permitir nulls.

2022-05-10 19:12 UTC, matiasgarcia requested changes
@gallotohugo deberias agregar el enum tambien en los Allowances... nada mas que no tendria el valor "unknown" que se usa para backfillear la bdd. Queda mas prolijo asi.

2022-05-10 19:35 UTC, gallottohugo commented on app/models/person.rb
> +  enum ipt: %i(usd_0
Si, es correcto!

2022-05-10 20:59 UTC, gallottohugo commented
@matiasgarcia DONE a todos los comentarios.

2022-05-10 21:03 UTC, matiasgarcia commented on app/models/allowance_base.rb
> +               usd_100000)
Podés usar la siguiente sintaxis:

enum tpi: { usd_5000_to_10000: 1, usd_10000_to_20000: 2, ... }

2022-05-10 21:19 UTC, matiasgarcia commented on app/models/person.rb
> +               usd_100000)
Tal vez podemos hacer lo mismo para el person, que quede bien explicitos los valores de integer...

incluso...

podria ser mas prolijo hacer

en person.rb

```
TPI_VALUES = { usd_5000_to_10000: 1, usd_10000_to_20000: 2 }.freeze
enum tpi: { unknown: 0 }.merge(TPI_VALUES)
```

y en allowance_base.rb el `enum tpi:` tiene el `TPI_VALUES`

2022-05-12 14:31 UTC, matiasgarcia approved these changes

2022-05-12 16:56 UTC, merged